/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthedEmployerIndexRouteImport } from './routes/_authed/employer/index'
import { Route as AuthedCandidateIndexRouteImport } from './routes/_authed/candidate/index'
import { Route as AuthedEmployerSubmissionsRouteImport } from './routes/_authed/employer/submissions'
import { Route as AuthedEmployerAssignmentsIndexRouteImport } from './routes/_authed/employer/assignments.index'
import { Route as AuthedEmployerAssignmentsNewRouteImport } from './routes/_authed/employer/assignments.new'
import { Route as AuthedCandidateSubmissionsNewRouteImport } from './routes/_authed/candidate/submissions.new'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedEmployerIndexRoute = AuthedEmployerIndexRouteImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCandidateIndexRoute = AuthedCandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmployerSubmissionsRoute =
  AuthedEmployerSubmissionsRouteImport.update({
    id: '/employer/submissions',
    path: '/employer/submissions',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedEmployerAssignmentsIndexRoute =
  AuthedEmployerAssignmentsIndexRouteImport.update({
    id: '/employer/assignments/',
    path: '/employer/assignments/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedEmployerAssignmentsNewRoute =
  AuthedEmployerAssignmentsNewRouteImport.update({
    id: '/employer/assignments/new',
    path: '/employer/assignments/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCandidateSubmissionsNewRoute =
  AuthedCandidateSubmissionsNewRouteImport.update({
    id: '/candidate/submissions/new',
    path: '/candidate/submissions/new',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/employer/submissions': typeof AuthedEmployerSubmissionsRoute
  '/candidate/': typeof AuthedCandidateIndexRoute
  '/employer/': typeof AuthedEmployerIndexRoute
  '/candidate/submissions/new': typeof AuthedCandidateSubmissionsNewRoute
  '/employer/assignments/new': typeof AuthedEmployerAssignmentsNewRoute
  '/employer/assignments/': typeof AuthedEmployerAssignmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/employer/submissions': typeof AuthedEmployerSubmissionsRoute
  '/candidate': typeof AuthedCandidateIndexRoute
  '/employer': typeof AuthedEmployerIndexRoute
  '/candidate/submissions/new': typeof AuthedCandidateSubmissionsNewRoute
  '/employer/assignments/new': typeof AuthedEmployerAssignmentsNewRoute
  '/employer/assignments': typeof AuthedEmployerAssignmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authed/employer/submissions': typeof AuthedEmployerSubmissionsRoute
  '/_authed/candidate/': typeof AuthedCandidateIndexRoute
  '/_authed/employer/': typeof AuthedEmployerIndexRoute
  '/_authed/candidate/submissions/new': typeof AuthedCandidateSubmissionsNewRoute
  '/_authed/employer/assignments/new': typeof AuthedEmployerAssignmentsNewRoute
  '/_authed/employer/assignments/': typeof AuthedEmployerAssignmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/employer/submissions'
    | '/candidate/'
    | '/employer/'
    | '/candidate/submissions/new'
    | '/employer/assignments/new'
    | '/employer/assignments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/employer/submissions'
    | '/candidate'
    | '/employer'
    | '/candidate/submissions/new'
    | '/employer/assignments/new'
    | '/employer/assignments'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth/login'
    | '/_authed/employer/submissions'
    | '/_authed/candidate/'
    | '/_authed/employer/'
    | '/_authed/candidate/submissions/new'
    | '/_authed/employer/assignments/new'
    | '/_authed/employer/assignments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/employer/': {
      id: '/_authed/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof AuthedEmployerIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/candidate/': {
      id: '/_authed/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof AuthedCandidateIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employer/submissions': {
      id: '/_authed/employer/submissions'
      path: '/employer/submissions'
      fullPath: '/employer/submissions'
      preLoaderRoute: typeof AuthedEmployerSubmissionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employer/assignments/': {
      id: '/_authed/employer/assignments/'
      path: '/employer/assignments'
      fullPath: '/employer/assignments/'
      preLoaderRoute: typeof AuthedEmployerAssignmentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/employer/assignments/new': {
      id: '/_authed/employer/assignments/new'
      path: '/employer/assignments/new'
      fullPath: '/employer/assignments/new'
      preLoaderRoute: typeof AuthedEmployerAssignmentsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/candidate/submissions/new': {
      id: '/_authed/candidate/submissions/new'
      path: '/candidate/submissions/new'
      fullPath: '/candidate/submissions/new'
      preLoaderRoute: typeof AuthedCandidateSubmissionsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedEmployerSubmissionsRoute: typeof AuthedEmployerSubmissionsRoute
  AuthedCandidateIndexRoute: typeof AuthedCandidateIndexRoute
  AuthedEmployerIndexRoute: typeof AuthedEmployerIndexRoute
  AuthedCandidateSubmissionsNewRoute: typeof AuthedCandidateSubmissionsNewRoute
  AuthedEmployerAssignmentsNewRoute: typeof AuthedEmployerAssignmentsNewRoute
  AuthedEmployerAssignmentsIndexRoute: typeof AuthedEmployerAssignmentsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedEmployerSubmissionsRoute: AuthedEmployerSubmissionsRoute,
  AuthedCandidateIndexRoute: AuthedCandidateIndexRoute,
  AuthedEmployerIndexRoute: AuthedEmployerIndexRoute,
  AuthedCandidateSubmissionsNewRoute: AuthedCandidateSubmissionsNewRoute,
  AuthedEmployerAssignmentsNewRoute: AuthedEmployerAssignmentsNewRoute,
  AuthedEmployerAssignmentsIndexRoute: AuthedEmployerAssignmentsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
